# Generated by Django 4.0.10 on 2026-04-12 17:02

import Home.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('episode_number', models.CharField(default='E01 - Serial Name', max_length=50)),
                ('download_link1080', models.CharField(blank=True, max_length=650, null=True)),
                ('download_link720', models.CharField(blank=True, max_length=650, null=True)),
                ('download_link480', models.CharField(blank=True, max_length=650, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField(max_length=2000)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('season_name', models.CharField(default='S01 - Serial Name', max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('Episodes', models.ManyToManyField(default=None, to='Home.episode')),
            ],
        ),
        migrations.CreateModel(
            name='Serial',
            fields=[
                ('Serial_name', models.CharField(max_length=200)),
                ('release_date', models.CharField(default='None', max_length=70)),
                ('short_intro', models.TextField(max_length=700)),
                ('IMDb_RATING', models.CharField(default=None, max_length=50)),
                ('poster', models.ImageField(upload_to='Posters/')),
                ('seriel_page_poster', models.ImageField(blank=True, null=True, upload_to='Posters/SerialPage/')),
                ('summary', models.TextField(max_length=1600)),
                ('trailer_file', models.FileField(blank=True, null=True, storage=Home.models.get_trailer_storage, upload_to='Trailers/')),
                ('page_view', models.IntegerField(default=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('director', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Home.director')),
                ('episodes', models.ManyToManyField(default=None, to='Home.episode')),
                ('genre', models.ManyToManyField(to='Home.genre')),
                ('seasons', models.ManyToManyField(default=None, to='Home.season')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='HomePageModel',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('release_date', models.CharField(default='None', max_length=70)),
                ('short_intro', models.TextField(max_length=700)),
                ('IMDb_RATING', models.CharField(default=None, max_length=50)),
                ('poster', models.ImageField(upload_to='Posters/')),
                ('movie_page_poster', models.ImageField(blank=True, null=True, upload_to='Posters/MoviePage/')),
                ('summary', models.TextField(max_length=1600)),
                ('trailer_file', models.FileField(blank=True, null=True, storage=Home.models.get_trailer_storage, upload_to='Trailers/')),
                ('download_link_1080', models.CharField(blank=True, max_length=650, null=True)),
                ('download_link_720', models.CharField(blank=True, max_length=650, null=True)),
                ('download_link_480', models.CharField(blank=True, max_length=650, null=True)),
                ('page_view', models.IntegerField(default=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('director', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Home.director')),
                ('genre', models.ManyToManyField(to='Home.genre')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.AddField(
            model_name='episode',
            name='chose_season',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Home.season'),
        ),
        migrations.CreateModel(
            name='comments_serial',
            fields=[
                ('name', models.CharField(default='Guest', max_length=200)),
                ('body', models.TextField(blank=True, max_length=650, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('serial_page', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments_serial', to='Home.serial')),
            ],
        ),
        migrations.CreateModel(
            name='comments',
            fields=[
                ('name', models.CharField(default='Guest', max_length=200)),
                ('body', models.TextField(blank=True, max_length=650, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('movie_page', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='Home.homepagemodel')),
            ],
        ),
    ]
