# Generated by Django 4.0.10 on 2026-04-12 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0020_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagemodel',
            name='trailer_file',
            field=models.FileField(blank=True, null=True, upload_to='Trailers/'),
        ),
        migrations.AddField(
            model_name='serial',
            name='trailer_file',
            field=models.FileField(blank=True, null=True, upload_to='Trailers/'),
        ),
    ]
