# Generated by Django 4.0.10 on 2026-04-12 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0021_homepagemodel_trailer_file_serial_trailer_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepagemodel',
            name='trailer',
        ),
        migrations.RemoveField(
            model_name='serial',
            name='trailer',
        ),
    ]
